# Generated by Django 3.1.6 on 2021-04-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionbids_auctioncomment_auctionlisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='Categories',
            field=models.CharField(choices=[('Books', 'Books'), ('Video Games', 'Video Games'), ('Trading Cards', 'Trading Cards'), ('Others', 'Others')], default='Video Games', max_length=64),
        ),
    ]
