# Generated by Django 3.1.6 on 2021-04-20 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlisting_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='Categories',
        ),
        migrations.AddField(
            model_name='auctioncategory',
            name='auctionlist',
            field=models.ManyToManyField(related_name='category', to='auctions.AuctionListing'),
        ),
        migrations.AddField(
            model_name='auctioncategory',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
