# Generated by Django 3.1.6 on 2021-04-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210426_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='watching',
            new_name='watch',
        ),
    ]
