# Generated by Django 3.1.6 on 2021-04-28 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210428_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctioncategory',
            name='auctionlist',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctioncategory', to='auctions.auctioncategory'),
        ),
    ]
