# Generated by Django 3.1.6 on 2021-04-30 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210428_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='comments',
        ),
        migrations.AddField(
            model_name='auctionbids',
            name='currentbiduserid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='auctioncomment',
            name='auctioncomments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='auctions.auctionlisting'),
        ),
        migrations.AddField(
            model_name='user',
            name='userbought',
            field=models.ManyToManyField(related_name='userbought', to='auctions.AuctionListing'),
        ),
        migrations.AddField(
            model_name='user',
            name='usersold',
            field=models.ManyToManyField(related_name='usersold', to='auctions.AuctionListing'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='usercommentlist',
        ),
        migrations.AddField(
            model_name='user',
            name='usercommentlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercomment', to='auctions.auctioncomment'),
        ),
    ]
