# Generated by Django 3.1.6 on 2021-04-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210430_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userlist',
            field=models.ManyToManyField(related_name='userlist', to='auctions.AuctionListing'),
        ),
    ]
