# Generated by Django 3.1.6 on 2021-04-30 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_user_userlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userbought',
            field=models.ManyToManyField(blank=True, related_name='userbought', to='auctions.AuctionListing'),
        ),
        migrations.AlterField(
            model_name='user',
            name='usercommentlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercomment', to='auctions.auctioncomment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userlist',
            field=models.ManyToManyField(blank=True, related_name='userlist', to='auctions.AuctionListing'),
        ),
        migrations.AlterField(
            model_name='user',
            name='usersold',
            field=models.ManyToManyField(blank=True, related_name='usersold', to='auctions.AuctionListing'),
        ),
    ]
