# Generated by Django 3.1.6 on 2021-05-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auctionlisting_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usercommentlist',
        ),
        migrations.AddField(
            model_name='user',
            name='usercommentlist',
            field=models.ManyToManyField(blank=True, related_name='usercomment', to='auctions.AuctionComment'),
        ),
    ]
